# Generated by Django 4.0 on 2022-11-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_votecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollitem',
            name='poll',
        ),
        migrations.DeleteModel(
            name='VoteCheck',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollItem',
        ),
    ]
